---
- name: remove mytop from deb
  apt:
    name: mytop
    state: absent

- name: check mytop
  stat: path=/usr/bin/mytop
  register: mytopPresent

- name: clone gregorg's mytop
  git: repo=https://github.com/gregorg/mytop.git dest=/tmp/mytop
  when: not mytopPresent.stat.exists
  register: gitMytop

- name: install mytop
  command: mv /tmp/mytop/mytop /usr/bin/mytop
  when: gitMytop|changed
